[project]
name = "simple-rss-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kaushal Bundel", email = "kaushalbundel@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "feedparser>=6.0.14",
    "nh3>=0.3.7",
    "rich>=15.0.0",
]

[project.scripts]
simple-rss-reader = "simple_rss_reader:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
